# Server configuration
bind = ":8080"  # Address to bind to (default: ":8080")
workers = 4     # Number of worker threads (default: 1)

# Redis configuration (optional)
# If not provided, will use static backend configuration below
redis = "redis://localhost:6379"

# HTTPS configuration
https = false
# cert_file = "cert.pem"  # Required if https = true
# key_file = "key.pem"    # Required if https = true

# Rate limiting
# rate_limit = 100        # Requests per 10 seconds
# rate_limit_page = "rate_limit.html"

# Server header configuration
server_header = "Rusty LoadBalancer"  # Set custom Server header
# server_header = ""      # Remove Server header completely

# Static backend configuration (used when Redis is not configured)
default_backends = [
    "localhost:8081",
    "localhost:8082"
]

# Host-specific backend configuration
[backends]
"example.com" = [
    "localhost:9001",
    "localhost:9002"
]
"api.example.com" = [
    "localhost:9003",
    "localhost:9004"
] 